### ISSUE TITLE
Link to bootyhuntergame.com on project page should be HTTP

### ISSUE THREAD

**Issue by chuckhoupt** [cbcerquiaga/BootyHunter#131]
The project link is currently HTTP**S**, but I don't think Github Pages supports HTTP**S** for custom domains. Clicking on the link leads to a SSL error.

For the moment, using the canonical `http://bootyhuntergame.com` might be best.

There are various options to securely host the site that @tahoupt or I can suggest.

**Comment by cbcerquiaga** [comment]
Fixed. Thank you.
