### ISSUE TITLE
Make the ship bounce off of islands when they collide

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/BootyHunter#18]

**Comment by cbcerquiaga** [comment]
Alternatively, we can make the ship impervious to damage for a short time after taking damage. Perhaps it can blink slowly, then blink quickly before returning to a normal state of being able to take damage

**Comment by cbcerquiaga** [comment]
Bouncing has something to do with the sprite.body.bounce.setTo() function, but I couldn't get it to work.

**Comment by cbcerquiaga** [comment]
If we get this working, it should hopefully bounce the ship off of the island if an island spawns at dead center, only damaging the player one instead of insta-killing them with the "black flash". Alternatively, we can have a spawn function that puts the ship as close as possible to the center without putting it within something like 50 pixels from any island

**Comment by dcoollx** [comment]
You guys looking for help? I would be happy to take a look at this issue

**Comment by cbcerquiaga** [comment]
Sure, if you want. Thanks!

**Comment by cbcerquiaga** [comment]
Thanks, mysterious stranger
