### ISSUE TITLE
Fix bug with infinitely looping bullets

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/BootyHunter#2]
If the ship is traveling east-west or north-south and fires cannonballs, then they will wrap around the world infinitely, and won't stop even if they pass the kill distance.

**Comment by dzwiener** [comment]
The bullets are automatically killed when they exceed bulletDistance pixels away from their original launch position. If the distance = 400 and the height of the map is 560 as long as your ship is towards the center of the map you can cause infinite bullets.

**Comment by cbcerquiaga** [comment]
So should we just shorten bulletDistance?

**Comment by dzwiener** [comment]
Or we could just implement a timer for each bullet such as .5 seconds that way it would resolve this infinitely wrapping problem and it would be able to go longer or shorter without concerns to the screen size.

**Comment by cbcerquiaga** [comment]
We can play with the length to make the game balanced, but if you think that will work, then we should do it.

**Comment by cbcerquiaga** [comment]
Switching the bullet kill type to lifespan fixed it.
