### ISSUE TITLE
Fix bullet wrapping

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/BootyHunter#3]
A lot of the time, bullets won't wrap around the world properly. Instead, they just barely cross the edge of the map and then die.

**Comment by dzwiener** [comment]
Do you want bullets to continually wrap around the map over and over again? When do you want them to die?

**Comment by cbcerquiaga** [comment]
No. We want them to wrap around the world once, then die once they've reached their kill distance

**Comment by cbcerquiaga** [comment]
Switching to kill lifespan fixed it
