### ISSUE TITLE
Create pirate fact text file

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/BootyHunter#31]

**Comment by dzwiener** [comment]
What is this issue about? Is it like a file to grab splash text from?

**Comment by cbcerquiaga** [comment]
On the game over screen, I think it'd be funny to have a random historically accurate pirate fact along with your game data. So to do that, we need a big text file with lots of one or two sentence pirate facts.

**Comment by dzwiener** [comment]
Committed a draft of this file, mostly copied from several websites. We should find one good source and cite them in our game.

**Comment by cbcerquiaga** [comment]
Sweet! Should we mix in a few tutorial tips, too? Say, 90% pirate facts, 10% hints?

**Comment by cbcerquiaga** [comment]
We can always add more, but we have 44 now
