### ISSUE TITLE
Game Occasionally starts with you stuck inside an island

### ISSUE THREAD

**Issue by dcoollx** [cbcerquiaga/BootyHunter#59]
I played a game where I spawned inside an island and could not move.

**Comment by cbcerquiaga** [comment]
I think what happened is that the ship wanted to bounce off of the island, but had nowhere to bounce. The plan is to check if there is an island in the center of the game, and if there is search for a space big enough for the player to sail around. Alternatively, we could find a way to check if the ship has spawned on the island, temporarily turn off bouncing (and damage) until the player leaves.
