### ISSUE TITLE
Slicing ships

### ISSUE THREAD

**Issue by dzwiener** [cbcerquiaga/BootyHunter#68]
Either two ships spawned in the same spot with the same speed or when I hit a shit one bounced up and another one stayed on course. This may be a bug.

**Comment by cbcerquiaga** [comment]
I think it's more likely that they spawned in the same place...Math.random() isn't a perfect way to find a place to spawn enemies, but I haven't been able to get spawning without overlapping (which we need to keep the player from spawning dead center, too) working. Probably the one with the higher z-value got hit and the other one didn't, which made the one change course and the other not.

**Comment by dzwiener** [comment]
Is this still an issue?

**Comment by cbcerquiaga** [comment]
Usually if it happens enemies kill each other before they get to the player.

**Comment by dzwiener** [comment]
So a bug turned into a feature?

**Comment by cbcerquiaga** [comment]
No...uh...I planned it like that all along
